### ISSUE TITLE
UI enhancements: RSVP, Add to Calendar 

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#111]
Make Add to Calendar also a box instead of link. 

Change RSVP box color to blue or some other color when not RSVPed and Green when RSVPed.

**Comment by nikhilym** [comment]
>> Make Add to Calendar also a box instead of link.
This has been done as per category addition to Event Details page.

>>Change RSVP box color to blue or some other color when not RSVPed and Green when RSVPed.
Seems non-critical to me.

**Comment by chandanatl** [comment]
Changed the color of buttons as per the above comment
