### ISSUE TITLE
Pass org. id and userid to Org. page and my events page

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#118]
Pass id of user in case of attendee and org. id in case of organizer when user/organizer clicks on "My Events"/"Org Details" in the dropdown.

**Comment by nikhilym** [comment]
MyEvents doesn't need user id since it picks up rsvp'ed events of currently logged in users.

**Comment by nikhilym** [comment]
Added org id to all page dictionaries in views. Changed base.html, to
set org_id in href for My Page link for Organization. Also changed Event
Details, to set the categories come in the same format as other
attributes.
