### ISSUE TITLE
No RSVP for organizer

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#121]
Right now we don't have RSVP for organizers. Disable RSVP or organizers or don't show on the page.

It says "Your RSVP has been saved successfully!" but it seems it never does that. That is good but don't show any such option.

**Comment by chandanatl** [comment]
Fixed this by checking if the user who's logged in is an organizer. Removed the RSVP option if it is an organizer.
