### ISSUE TITLE
UI issues on Homepage

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#122]
All event cards not same height. Check screenshot. 

<img width="705" alt="capture" src="https://user-images.githubusercontent.com/22849134/33696420-0a9eba4e-dab7-11e7-921d-577b1f0e68ca.PNG">

**Comment by nikhilym** [comment]
This is not possible on Current Events list since the cards have Name, Start Date, Time, Location and Hashtags to be shown. All these columns are not null in DB and should have a value. This will be fixed once the issue #116 is fixed with respective validations

**Comment by kdhiman0309** [comment]
The problem is with height of the bottom box. We can fix the height so that all box are of equal size.

**Comment by nikhilym** [comment]
Yes, This shouldn't be different for different events, considering all events will have time, location and tags defined.

**Comment by nikhilym** [comment]
Issue #116 is fixed. Update all events that miss location/hashtags from backend and retest the feature.

**Comment by nikhilym** [comment]
Reopen the issue if this still exists after setting all mandatory attributes for events.
