### ISSUE TITLE
Event Upload screen uploading event time wrongly

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#35]
During Event Upload testing, I observed that the event upload screen is not saving the time selected for the event correctly. I could see that after successful event submission, when I check the event details, the time is coming as 12:00 AM by default.

**Comment by kolasanichaitanya** [comment]
I tired this. Looks like it is working fine
![image](https://user-images.githubusercontent.com/4915491/33055328-bf783142-ce33-11e7-8bb2-a38abb7baf3c.png)

Moving this Review/QA untill someone confirms independently.

**Comment by kdhiman0309** [comment]
Works fine. Closing the issue.
