### ISSUE TITLE
Schema setup for storing common registration details of user

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#41]
A common schema (table) has to be created, that can store registration information about event attendees and event organizers, which is supplied during registration process

**Comment by nikhilym** [comment]
Looking at the [Customizing Authentication in Django](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/) documentation

**Comment by nikhilym** [comment]
There are 4 approaches possible, as mentioned in the official documentation : 
1. Proxy Model - Creating a proxy for User Tabel and letting Django handle auth
2. User Profile - Adding some non-auth related attributes to User and letting Django handle auth
3. Customer User Model from AbstractBaseUser - If Django auth doesn't fit the need (like changing what is the auth fields, not the by default username field)
4. Customer User Model from AbstractUser - Not overriding auth but only User Model

As documentation states, models 3 and 4 would ideally need to be done before creating users on the application. Else there is a whole lot of details to be done for migrating users to new models. 

Currently looking at other blogs like [1](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html), [2](https://blog.khophi.co/extending-django-user-model-userprofile-like-a-pro/) etc. to see which one fits well with our needs. As of now, model 2 seems to be a good fit.

Will be updating the issue with which model is finally decided upon

**Comment by kolasanichaitanya** [comment]
![image](https://user-images.githubusercontent.com/4915491/33055460-a699a484-ce34-11e7-87dd-dd36556633de.png)

![image](https://user-images.githubusercontent.com/4915491/33055477-c1f810c6-ce34-11e7-970b-5411c211cb7e.png)
![image](https://user-images.githubusercontent.com/4915491/33055487-d047e05c-ce34-11e7-936f-143c7e0133c3.png)


CC: @nikhilym  - this may be useful for DB schema setup.

**Comment by nikhilym** [comment]
@kolasanichaitanya This is great. Just couple of observations : 
1. New Attendee and New Organization are two tabs? Internally I am storing a boolean flag 'user_is_organization'. So the register button should handle the case which one is being registered. Do you think this way is better or having a radio button and rending the sections when corresponding option is selected is better?

2. I have a single address field rather than address, city and zip. do we need it to be that granular?

3. Username is our unique identifier. So we need a username field in both attendee and org registration.

4. I plan to put 'image' field for both kind of users. So that needs to be added too. 

Let me know your thoughts. I am done with the models. Currently testing auto save functionality when we create a User and the corresponding values are saved in other tables as well. Will update the issue once it is done.

**Comment by nikhilym** [comment]
Also, @kolasanichaitanya , upload these screens on the UI issue as the first versions. I guess that would be easier to track too.

**Comment by kolasanichaitanya** [comment]
@nikhilym 
1. I think this way is better. We can handle the user_is_organization in views code based on the page from which request is received. 
2. Need not be this granular. I can handle appending all the strings and submitting a single address string to API. We can leave the UI as is. 
3. I will add that.
4. I will add a image upload button button and may be name it Profile Picture .

**Comment by nikhilym** [comment]
@kolasanichaitanya  Thanks for the update. Agree with you

As an update on the DB model, I am done with the models. I am trying to write triggers (using post_Save [Django Signals](https://docs.djangoproject.com/en/1.11/topics/signals/)), so that once a user is created, it will automatically create profile and details accordingly.

**Comment by nikhilym** [comment]
Triggering seems to be the wrong approach here since creating a signal on post-save of User will not give information about UserProfile or OrganizationDetails. Similarly, creating a signal on post-save of UserProfile doesn't help us whether OrganizationDetails are filled up or not. We can always have a validator on views.py side, to do the checking, rather than on the DB side.
