### ISSUE TITLE
Sign Up page UI template

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#44]
Create a Registration Form Page that handles registration for both Event Attendees and Event Organizers (depending upon a checkbox/radio button etc.), by providing all the fields mentioned in the user story. The page should also show errors in case of invalid registration or in case all the required fields are not provided.

**Comment by kolasanichaitanya** [comment]
I added a Initial version of signup page to the code base. May require minor changes based on the db schema

**Comment by kolasanichaitanya** [comment]
![image](https://user-images.githubusercontent.com/4915491/33055477-c1f810c6-ce34-11e7-970b-5411c211cb7e.png)
![image](https://user-images.githubusercontent.com/4915491/33055487-d047e05c-ce34-11e7-936f-143c7e0133c3.png)

Screens from first draft added

**Comment by nikhilym** [comment]
Tested the latest signup/login integration. Following are some observations : 

1. The tab "New Organization" doesn't get selected when clicked on Signup page. However, the form does change to "Organization" related fields.
2. Let's put the 'Register' button in the center maybe? That will look more aesthetic I guess.
3. We need a cancel button to let user cancel the registration anytime. or a clear button to clear all form fields? I think this is needed for form cleaning on different users signing up from same browser.
4. Can we include a captcha during registration? You can look at [Django-simple-captcha](http://django-simple-captcha.readthedocs.io/en/latest/usage.html) add-on.
5. The alert location after successful signup seems to be wrong. Can we change it to popup or something? Also there is a typo in the signup message.

I guess since this is still under development, the navigation after login is to a separate page. Think it has to go to homepage itself with logged in user info shown someplace. We can discuss about this. Great work 👍

**Comment by kolasanichaitanya** [comment]
Cancel and Captcha can be added in a separate enhancement issue. Closing this
