### ISSUE TITLE
Integrate Sign Up page with existing application

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#45]
Integrate the registration page with the existing application, by providing links to navigate to the registration page and handling permissions for links to render/page navigation accordingly.

**Comment by nikhilym** [comment]
Assigned to @kolasanichaitanya  since he is already working on it (worked on it and in the verge of finishing)

**Comment by kolasanichaitanya** [comment]
This is completed. Any minor issues found in testing will be fixed under new issues
