### ISSUE TITLE
API to get organization details from the DB

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#55]
Develop an API to fetch an organization details, given organization’s id, from the DB

**Comment by nikhilym** [comment]
How are you getting the organization id, to send it to API? From the login information (request.user.id ?) Since the UserProfile and OrganizationDetails model changed as per Signup/Login implementation by @kolasanichaitanya , I will be needing the exact details on which id will be sent over to the API, to fetch the values accordingly.

**Comment by kolasanichaitanya** [comment]
When the user logs in we can set a global boolean to indicate current user is a user or a org (or) You can use the existing API check_user_name() with a little modification to take in request.user.user_name to first check if the user is user or org and then fetch the actual org id using the user_name(As user_name is replicated inside these tables this should be fairly easy).

CC: @kdhiman0309

**Comment by nikhilym** [comment]
I like the second idea. Then the api will take in a username object. @kdhiman0309 need your input on how the API should behave, so that I can go forward with coding it.

**Comment by kdhiman0309** [comment]
I will get the org. ID from event details. For that I asked to added organizer id when creating an event. So, on search page and on event details page, id of org. Can be found in an  "Event"

This is the only way to navigate to org. Details page since we don't have separate search for an organization.

**Comment by kolasanichaitanya** [comment]
Then should we add id to user and org tables ? or this works with the id generated for django user which is a internal reference in both these tables ?
CC: @nikhilym

**Comment by nikhilym** [comment]
We have an id column for both UserProfile and Org.Details table generated (Even with our current implementation). We can use that to tag event with id. But that would depend on the implementation of who are allowed to create events. Are we allowing only orgs to create events? If so, then this would work. If not, then we need to think how to handle id's from two different model objects where id's might clash.
@kdhiman0309 , @kolasanichaitanya

**Comment by kolasanichaitanya** [comment]
The last time we discussed only Organizations can create events. In-fact I would say event upload will be visible only when logged in as Org.

**Comment by kdhiman0309** [comment]
Only organizer can create an event. When a org. is logged in you and he/she creates an event, we stored a field in event details, org. id.

**Comment by nikhilym** [comment]
Cool, then we can stick with org_id being populated under events model and using the org id, org details can be fetched. Will work on the API accordingly.

**Comment by nikhilym** [comment]
Added get_org_details under apis.py, to get organization details when an
organization id is passed as input. In case the object doesn't exist in
db, a None object is returned.
