### ISSUE TITLE
Testing organization page

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#58]
Test this page using the scenarios mentioned in the BDD scenarios. Test the navigation from other pages to organization page

Acceptance Criteria: (presented as Scenarios)
Scenario 1: Navigating to the Organization Page
	Given user is on search listing page/my events/event details page
	When he/she clicks on organization name in the event card
	Then he/she is navigated to a the organization page

Scenario 2: User lands on organization page
Given the user is on an organization page
	When organization details are valid
           Then show organization’s name on top
           And show organization’s logo/image on left top
           And show organization’s description
           When organization’s contact email is available (present) 
           Then show organization’s contact email
           When organization’s contact address is available
           Then show organization’s contact address
           When organization’s contact phone number is available 
           Then show organization’s contact phone number

**Comment by devykulk** [comment]
Tested the scenarios
