### ISSUE TITLE
My Events page

### ISSUE THREAD

**Issue by devykulk** [UCSD-CSE-210/UCSDEventHub#64]
This page shows the logged in user’s upcoming events which they RSVP'd to as a list view
As a website user (attendee)
I want to see a My Events page
So that I can view the events that I have RSVP’d to

Acceptance Criteria: (presented as Scenarios)

Scenario 1: Navigating to the My Events Page
Given user is on homepage/search listing page/event details page
And the user is logged in
When he/she clicks on the “My Events” button on the toolbar in the header
Then he/she is navigated to the My Events page

Scenario 2: User lands on My Events page
Given the user is on the My Events page
When the user has event(s) that he/she has RSVP’d to, namely "FunRun 5k" and "Christmas with friends", and these events happen in the same order date-wise
Then show these events as a scrollable list view similar to the search results page in the order of increasing date.

Scenario 3: User wants to see event details for event he/she has RSVP’d to
Given the user is on the My Events page 
When the user clicks on an event from the list named "FunRun 5k"
Then he/she should be navigated to the event details page for that event

**Comment by nikhilym** [comment]
All issues under epic finished.
