### ISSUE TITLE
Login/Authentication Controller

### ISSUE THREAD

**Issue by kolasanichaitanya** [UCSD-CSE-210/UCSDEventHub#71]
Design a django model class to handle the authentication of the user(both individual users and as an organisation). The design has to work well with django’s MVC pattern.

**Comment by nikhilym** [comment]
This is already pushed by @kolasanichaitanya , as per Application Login/Signup template changes. Closing this. (Commit - https://github.com/UCSD-CSE-210/UCSDEventHub/commit/254730a9e241cf859eec4340c14d6f7a881dd311)
