### ISSUE TITLE
Integrate Logout

### ISSUE THREAD

**Issue by kolasanichaitanya** [UCSD-CSE-210/UCSDEventHub#72]
Integrate logout as a link in the main site nav bar. The logout link should be visible to logged in user’s and upon click should log them out of the site and present the home page UI similar to when the user is not logged in.

**Comment by nikhilym** [comment]
This is already pushed by @kolasanichaitanya , as per Application Login/Signup template changes. Closing this. (Commit - https://github.com/UCSD-CSE-210/UCSDEventHub/commit/254730a9e241cf859eec4340c14d6f7a881dd311)
