### ISSUE TITLE
Get popular upcoming events API

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#76]
Change the sorting function to get upcoming events by RSVP count + start date and start time of events, which was created as per the search events API created per issue #19

**Comment by nikhilym** [comment]
Added additional sort of checking RSVP count for upcoming events in the
upcoming_events() api in apis.py. The RSVP count for each event that is
filtered as per the current time, is found by using the newly written
api get_rsvp_count, which takes in an event_id as input and returns a
count of number of users that RSVP'ed to the event. Now, the sort
sequence is in the following format : Max RSVP Count, Earlier Start
Date, Earlier Start Time.

**Comment by kdhiman0309** [comment]
API doesn't return events with RSVP count=0.
I create a fresh event. There are no upcoming events before. This created event doesn't show up on homepage. I can find it on search page and event details page.

**Comment by kdhiman0309** [comment]
I believe API is working fine but the integration is breaking so closing the issue.

**Comment by nikhilym** [comment]
>>API doesn't return events with RSVP count=0 or new events.
>>I create a fresh event. There are no upcoming events before. This created event doesn't show up on >>homepage. I can find it on search page and event details page.

@kdhiman0309 , This is as per the changes @devykulk did. we already have a bug #98 for this. I am expecting she is fixing this ASAP.
