### ISSUE TITLE
Test the popular upcoming events

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#77]
Write automated test cases for DB level verification and do manual testing for popular upcoming events section as mentioned in the BDD scenarios for the User Story.

Following are the BDD scenarios : 

Scenario 1: Viewing popular upcoming events
	Given that the user has entered the website’s URL
	When the homepage loads
	Then the list of upcoming events should be displayed in a grid/tile view 
  And these events are the most popular ones (the ones that have highest RSVP count)

Scenario 2: Viewing popular upcoming events in correct order
	Given that the user has entered the website’s URL
	When the homepage loads and popular upcoming events are shown
	Then the list of popular upcoming events , that have matching RSVP count, should be
              sorted with respect to event start_date

**Comment by kdhiman0309** [comment]
Tested as per BDD scenarios.
