### ISSUE TITLE
Should the HomePage show upcoming events even though User is logged in?

### ISSUE THREAD

**Issue by nikhilym** [UCSD-CSE-210/UCSDEventHub#98]
Since we have MyEvents page (@kdhiman0309 correct me if I am wrong), shouldn't HomePage show all upcoming events to even logged in user? Or if we are only showing the RSVP events, shouldn't the section name be changed to My Events? or two sections, one with Upcoming and one with My Events should be shown?

Currently, as per issue #82 , this is not the case.

**Comment by kdhiman0309** [comment]
Homepage shows all the popular upcoming events (same for all users) and My Events shows RSVP'd events to a logged in user (events RSVP'd by the user).

**Comment by nikhilym** [comment]
So, @devykulk can you please make the changes and push it? Please use this issue for fixing the page and also update the base issue #82 about this change.

**Comment by nikhilym** [comment]
Guess this is already fixed as per latest commit from @devykulk . closing this.
